export interface PresetItem {
  id: string;
  name: string;
  category: 'social' | 'video' | 'display' | 'photo' | 'cinema';
  platform?: string;
  ratioW: number;
  ratioH: number;
  ratioLabel: string;
  width: number;
  height: number;
  description: string;
  badge?: string;
}

export const PLATFORM_PRESETS: PresetItem[] = [
  // Social Media
  {
    id: 'yt-video',
    name: 'YouTube Video & Stream',
    category: 'video',
    platform: 'YouTube',
    ratioW: 16,
    ratioH: 9,
    ratioLabel: '16:9',
    width: 1920,
    height: 1080,
    description: 'Standard 1080p Full HD video uploads and live streams.',
    badge: 'Most Popular',
  },
  {
    id: 'yt-shorts',
    name: 'YouTube Shorts',
    category: 'video',
    platform: 'YouTube',
    ratioW: 9,
    ratioH: 16,
    ratioLabel: '9:16',
    width: 1080,
    height: 1920,
    description: 'Vertical short-form video feeds.',
  },
  {
    id: 'yt-thumb',
    name: 'YouTube Thumbnail',
    category: 'social',
    platform: 'YouTube',
    ratioW: 16,
    ratioH: 9,
    ratioLabel: '16:9',
    width: 1280,
    height: 720,
    description: 'Minimum 640px width; 1280x720 recommended for crisp rendering.',
  },
  {
    id: 'yt-banner',
    name: 'YouTube Channel Banner',
    category: 'social',
    platform: 'YouTube',
    ratioW: 16,
    ratioH: 9,
    ratioLabel: '16:9',
    width: 2560,
    height: 1440,
    description: 'Safe text area is 1546x423 in center.',
  },
  {
    id: 'ig-portrait',
    name: 'Instagram Portrait Feed',
    category: 'social',
    platform: 'Instagram',
    ratioW: 4,
    ratioH: 5,
    ratioLabel: '4:5',
    width: 1080,
    height: 1350,
    description: 'Takes maximum vertical screen space in mobile feeds.',
    badge: 'High Engagement',
  },
  {
    id: 'ig-square',
    name: 'Instagram Square Post',
    category: 'social',
    platform: 'Instagram',
    ratioW: 1,
    ratioH: 1,
    ratioLabel: '1:1',
    width: 1080,
    height: 1080,
    description: 'Classic square post format.',
  },
  {
    id: 'ig-story-reels',
    name: 'Instagram Reels & Stories',
    category: 'social',
    platform: 'Instagram',
    ratioW: 9,
    ratioH: 16,
    ratioLabel: '9:16',
    width: 1080,
    height: 1920,
    description: 'Full-screen mobile story and reel dimensions.',
  },
  {
    id: 'tt-video',
    name: 'TikTok Video',
    category: 'social',
    platform: 'TikTok',
    ratioW: 9,
    ratioH: 16,
    ratioLabel: '9:16',
    width: 1080,
    height: 1920,
    description: 'Vertical 1080x1920 standard for TikTok uploads.',
  },
  {
    id: 'x-post',
    name: 'X (Twitter) Feed Post',
    category: 'social',
    platform: 'X / Twitter',
    ratioW: 16,
    ratioH: 9,
    ratioLabel: '16:9',
    width: 1200,
    height: 675,
    description: 'Crisp preview in timeline without auto-crop.',
  },
  {
    id: 'x-header',
    name: 'X (Twitter) Header Banner',
    category: 'social',
    platform: 'X / Twitter',
    ratioW: 3,
    ratioH: 1,
    ratioLabel: '3:1',
    width: 1500,
    height: 500,
    description: 'Profile banner header.',
  },
  {
    id: 'li-post',
    name: 'LinkedIn Post Image',
    category: 'social',
    platform: 'LinkedIn',
    ratioW: 191,
    ratioH: 100,
    ratioLabel: '1.91:1',
    width: 1200,
    height: 627,
    description: 'Standard link preview and feed update size.',
  },
  {
    id: 'li-banner',
    name: 'LinkedIn Personal Banner',
    category: 'social',
    platform: 'LinkedIn',
    ratioW: 4,
    ratioH: 1,
    ratioLabel: '4:1',
    width: 1584,
    height: 396,
    description: 'Background header banner for personal profile.',
  },
  {
    id: 'pin-standard',
    name: 'Pinterest Standard Pin',
    category: 'social',
    platform: 'Pinterest',
    ratioW: 2,
    ratioH: 3,
    ratioLabel: '2:3',
    width: 1000,
    height: 1500,
    description: 'Recommended optimal pin aspect ratio.',
  },

  // Displays & Monitors
  {
    id: 'disp-4k',
    name: '4K Ultra HD Display',
    category: 'display',
    platform: 'Monitors',
    ratioW: 16,
    ratioH: 9,
    ratioLabel: '16:9',
    width: 3840,
    height: 2160,
    description: 'Modern 4K UHD monitors, TVs, and wallpapers.',
  },
  {
    id: 'disp-1440p',
    name: 'QHD 1440p Gaming',
    category: 'display',
    platform: 'Monitors',
    ratioW: 16,
    ratioH: 9,
    ratioLabel: '16:9',
    width: 2560,
    height: 1440,
    description: 'Popular high-performance desktop gaming monitor standard.',
  },
  {
    id: 'disp-ultrawide',
    name: '21:9 Ultrawide QHD',
    category: 'display',
    platform: 'Monitors',
    ratioW: 21,
    ratioH: 9,
    ratioLabel: '21:9',
    width: 3440,
    height: 1440,
    description: 'Curved ultrawide productivity and simulator gaming display.',
  },
  {
    id: 'disp-super-ultrawide',
    name: '32:9 Super Ultrawide',
    category: 'display',
    platform: 'Monitors',
    ratioW: 32,
    ratioH: 9,
    ratioLabel: '32:9',
    width: 5120,
    height: 1440,
    description: 'Dual QHD seamless super ultrawide monitors.',
  },
  {
    id: 'disp-macbook',
    name: 'MacBook Pro Retina (16:10)',
    category: 'display',
    platform: 'Apple',
    ratioW: 16,
    ratioH: 10,
    ratioLabel: '16:10',
    width: 3024,
    height: 1964,
    description: 'Apple 14-inch / 16-inch Liquid Retina XDR screen ratio.',
  },
  {
    id: 'disp-ipad',
    name: 'iPad Display (4:3)',
    category: 'display',
    platform: 'Apple',
    ratioW: 4,
    ratioH: 3,
    ratioLabel: '4:3',
    width: 2732,
    height: 2048,
    description: 'iPad Pro 12.9-inch native aspect resolution.',
  },

  // Cinema & Photography
  {
    id: 'cinema-imax',
    name: 'IMAX 70mm Film',
    category: 'cinema',
    platform: 'Cinema',
    ratioW: 143,
    ratioH: 100,
    ratioLabel: '1.43:1',
    width: 4096,
    height: 2864,
    description: 'True full-height 15-perf 70mm IMAX format (e.g. Oppenheimer).',
  },
  {
    id: 'cinema-anamorphic',
    name: 'Cinemascope / Anamorphic',
    category: 'cinema',
    platform: 'Cinema',
    ratioW: 239,
    ratioH: 100,
    ratioLabel: '2.39:1',
    width: 4096,
    height: 1714,
    description: 'Standard widescreen cinematic theatrical release ratio.',
  },
  {
    id: 'photo-35mm',
    name: '35mm DSLR Sensor (3:2)',
    category: 'photo',
    platform: 'Photography',
    ratioW: 3,
    ratioH: 2,
    ratioLabel: '3:2',
    width: 6000,
    height: 4000,
    description: 'Classic 24MP full-frame and APS-C camera sensor ratio.',
  },
  {
    id: 'photo-print-8x10',
    name: 'Classic 8x10 Print (5:4)',
    category: 'photo',
    platform: 'Print',
    ratioW: 5,
    ratioH: 4,
    ratioLabel: '5:4',
    width: 3000,
    height: 2400,
    description: 'Standard photographic portrait print ratio at 300 DPI.',
  }
];
